FORMAT: 1A
HOST: http://katastralniczmonitorbackend.apiblueprint.org/

# monitor.katastralni.cz

Monitor is a simple landuse data visualization.

## Administrative Units [/administrative_units]

### List All Administrative Units [GET]

+ Response 200 (application/json)

        [
            {
                "name": "municipality",
                "repr": "obec"
            }
        ]



## Dates [/dates]

### List All Dates [GET]

+ Response 200 (application/json)

        [
            {
                "date": '2016-01-01'
            }
        ]

# Group Cadastral Areas

## Retrieve Cadastral Area Statistics [/cadastral_areas/{code}/{date}]

### Get Cadastral Area By Id [GET]

+ Response 200 (application/json)

        {
            "code": 123456,
            "name": 'Židlochovice',
            "date": '2016-01-01',
            "stats": [{}]
        }

## Retrieve Similar Cadastral Areas [/cadastral_areas/{code}/similar]

### Get Similar Cadastres [GET]

+ Response 200 (application/json)

        {
            "similar": [
                {
                    "code": 123456,
                    "name": 'Židlochovice'
                }
            ]